---
title: "R Notebook"
output: html_notebook
---

We start by loading our results from the previous week

```{r}
library(DESeq2)
library(dplyr)
## Read the annotated results
results_tgf <- readRDS("Robjects/results_TGF_vs_CTR_annotated_BACKUP.rds")
## Read the counts that we produced previously
dds <- readRDS("Robjects/dds_BACKUP.rds")
```
# Exercise

The standard volcano plot can be produced with the `ggplot2` package

```{r}

library(ggplot2)
results_tgf %>% 
  ggplot(aes(x = log2FoldChange, y = -log10(padj))) + geom_point()
```

```{r}
library(org.Hs.eg.db)
ecm_anno <- AnnotationDbi::select(org.Hs.eg.db,
                                 keys = "GO:0030198",
                                 keytype = "GO",
                                 columns=c("ENSEMBL","SYMBOL"))
ecm_anno
```

```{r}
ecm_ids <- pull(ecm_anno, "ENSEMBL")
```

```{r}
results_tgf %>% 
  mutate(ECM_Gene = ENSEMBL %in% ecm_ids) %>% 
  ggplot(aes(x = log2FoldChange, y = -log10(padj),col=ECM_Gene)) + geom_point()
```

